apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: builder-pvc-2
  annotations:
    "helm.sh/resource-policy": keep
spec:
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi